### ISSUE TITLE
epg uids not unique => causing ghost timers in kodi tv guide

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.dvblink#57]
https://github.com/kodi-pvr/pvr.dvblink/blob/master/src/DVBLinkClient.cpp#L841

=> xbmcTimer.iEpgUid = rec->GetProgram().GetStartTime();

and

https://github.com/kodi-pvr/pvr.dvblink/blob/master/src/DVBLinkClient.cpp#L1664

=> broadcast.iUniqueBroadcastId = p->GetStartTime();

This is in in no way unique as many different epg events may have the same start date and time.  Kodi relays on real uniqueness of the epg uids!

For more details regarding this bug from users pov see here: http://forum.kodi.tv/showthread.php?tid=291649

**Comment by ksooo** [comment]
ping @dvblogic

**Comment by dvblogic** [comment]
@ksooo Thanks of your investigation!
Was it changed in Krypton, comparing to an earlier version? It used to be unique for a channel if I remember correctly.
Anyway, it was a very unfortunate choice to make broadcast id and epg id in Kodi integers, instead of making it a more generic string. DVBLink keeps program ids and timer ids as strings inside. 
I am not sure what is the good way to solve it, yet. Maybe we will build a temporary hash table inside the add-on.

**Comment by ksooo** [comment]
@dvblogic thought about all this a little longer. I was thinking that epg event ids have to be unique for the addon, but there is no proof for this, because there is no clear documentation (at least I was not able to find some). It seems that at least some addon implementations (e.g. dvblink, dvbviewer) implemented the ids unique for a channel. So, my assumption on uniqueness may just have been wrong.

So, I decided not to break those channel unique implementations and to adapt kodi pvr code instead to always compare event uids plus there channel uids to check whether two events are the same or whether a timer belongs to an event. 

Additionally, I will adjust API documentation to be clear wrt uniqueness context.

So, this issue can be closed. Sorry for the noise.

**Comment by dvblogic** [comment]
@ksooo Thank you!
